name: "Format Deployment Role ARN"
description: "Format the full AWS ARN of an IAM Role used for deployment, given the Account ID and Role Name."
inputs:
  account-id:
    description: "The ID of the AWS Account that the Role is in."
    required: true
  project:
    description: ""
    required: true
  artifact:
    description: ""
    required: true
outputs:
  role-arn:
    description: "The ARN of the deployment Role."
    value: ${{ steps.format-arn.outputs.role-arn }}
runs:
  using: composite
  steps:
    - name: Format-ARN
      id: format-arn
      run: echo "role-arn=arn:aws:iam::${{ inputs.account-id }}:role/${{ inputs.project }}-${{ inputs.artifact }}-deployer" >> $GITHUB_OUTPUT
      shell: bash
