name: "Run Terraform"
description: "Setup Terraform for pipeline use, tf init, tf apply"
inputs:
  project:
    description: "The name of the project."
    required: true
  account:
    description: "The name of the account."
    required: true
  state-key:
    description: "The key against which Terraform state will be stored."
    required: true
  dir:
    description: "The directory which contains the Terraform module for creating deployment roles."
    required: false
    default: deployment-roles/
runs:
  using: "composite"
  steps:
    - name: Setup-Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.3
    - name: Terraform-Init
      working-directory: ${{ inputs.dir }}
      run: |
        terraform init -input=false -backend-config='bucket=state.terraform.${{ inputs.account }}.${{ inputs.project }}' -backend-config='dynamodb_table=lock.state.terraform.${{ inputs.account }}.${{ inputs.project }}' -backend-config='key=${{ inputs.state-key }}'
      shell: bash
    - name: Terraform-Apply
      working-directory: ${{ inputs.dir }}
      run: |
        terraform apply -input=false -auto-approve -lock=false
      shell: bash
