name: "Lookup Account ID from Name"
description: "Given a friendly name for an organizational account, finds it's corresponding account id."
inputs:
  account:
    description: "The name of the AWS Account we want the ID for."
    required: true
outputs:
  account-id:
    description: "The ID of the AWS Account that corresponds to the account name input"
    value: ${{ steps.lookup-account-id.outputs.account-id }}
runs:
  using: composite
  steps:
    - name: Apt-Install-AWS-CLI
      run: |
        sudo apt-get install awscli
        aws --version
        aws sts get-caller-identity
      shell: bash
    - name: List-Org-Accounts
      id: lookup-account-id
      run: |
        ACCOUNT_ID=$(aws organizations list-accounts --query "Accounts[?Name == '${{ inputs.account }}'].Id | [0]" --output text)
        echo "account-id=${ACCOUNT_ID}"
        echo "account-id=${ACCOUNT_ID}" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Assert-Account-ID-Present
      if: ${{ steps.lookup-account-id.outputs.account-id == '' }}
      run: |
        echo "Could not find Account ID from Account Name: '${{ inputs.account }}' (got: ${{ steps.lookup-account-id.outputs.account-id }})"; exit 1;
      shell: bash
